CREATE TABLE IF NOT EXISTS `users` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `login` TINYTEXT,
  `email` TINYTEXT,
  `password` TINYTEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `vk` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `userId` INT UNSIGNED NOT NULL UNIQUE,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `domain` TINYTEXT NOT NULL,
  `name` TINYTEXT,
  `surname` TINYTEXT,
  `nickname` TINYTEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
